use std::ops::Deref;

use crate::record::Record;

/// Generated by the [`xentrace_parse`](super::xentrace_parse) function,
/// contains the [records](crate::record::Record) of the parsed XenTrace binary files.
#[derive(Debug, Default)]
pub struct Trace {
    pub(crate) records: Box<[Record]>,
    pub(crate) cpu_count: u16,
}

impl Trace {
    /// Returns the number of [Records](crate::record::Record) that have been read from the trace file.
    ///
    /// **N.B.** This function returns the same value of `Trace::len()`.
    ///
    /// # Examples
    ///
    /// ```
    /// use std::io::Result;
    /// use xentrace_parser::{xentrace_parse, Trace};
    ///
    /// fn function() -> Result<()> {
    ///     let trace: Trace = xentrace_parse("/path/to/xentrace.bin")?;
    ///
    ///     let record_count = trace.record_count();
    ///     println!("{}", record_count);
    ///
    ///     Ok(())
    /// }
    /// ```
    pub fn record_count(&self) -> usize {
        self.records.len()
    }

    /// Returns the count of CPUs used in the trace file.
    ///
    /// **N.B.** The value is calculated based on the highest value
    /// in the list of CPUs used, the result may be inaccurate.
    ///
    /// # Examples
    ///
    /// ```
    /// use std::io::Result;
    /// use xentrace_parser::{xentrace_parse, Trace};
    ///
    /// fn function() -> Result<()> {
    ///     let trace: Trace = xentrace_parse("/path/to/xentrace.bin")?;
    ///
    ///     let cpu_count = trace.cpu_count();
    ///     println!("{}", cpu_count);
    ///
    ///     Ok(())
    /// }
    /// ```
    pub fn cpu_count(&self) -> u16 {
        self.cpu_count
    }
}

impl Deref for Trace {
    type Target = [Record];

    fn deref(&self) -> &Self::Target {
        &self.records
    }
}
